#!/bin/bash

sudo apt-get install tree -y

sudo apt-get install software-properties-common -y
sudo apt-get update

sudo add-apt-repository ppa:neovim-ppa/stable -y
sudo apt-get update
sudo apt-get install neovim
